### ISSUE TITLE
Gulp plugin?

### ISSUE THREAD

**Issue by ethikz** [matthewbdaly/grunt-blogbuilder#9]
Thought about making this a Gulp plugin as well? I could see quite a bit of value for that as well, myself included

**Comment by matthewbdaly** [comment]
I have thought about that and I'd like to do it, but it's a bit fiddlier because you have to pass through both the content and templates whereas with Grunt you can just specify them as configuration variables. Unfortunately I'm not likely to have time to do it anytime soon.

**Comment by ethikz** [comment]
@matthewbdaly Status?  If not then you can close it

**Comment by matthewbdaly** [comment]
Not likely to happen any time soon, I'm afraid. If you want to build one yourself based on this I'm happy to link to it, but I won't have the chance to do this myself.
